# us-west-1 is managed by cloudformation

us-west-2:
    default:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    masters:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.ffxbld.productdelivery.prod.mozaws.net: IGW
            upload.trybld.productdelivery.prod.mozaws.net: IGW
            upload.tbirdbld.productdelivery.prod.mozaws.net: IGW
            upload.ffxbld.productdelivery.stage.mozaws.net: NAT
            upload.trybld.productdelivery.stage.mozaws.net: NAT
            upload.tbirdbld.productdelivery.stage.mozaws.net: NAT
            # seabld only here to appease firewall-test complexity, no harm
            upload.seabld.productdelivery.prod.mozaws.net: IGW
            upload.seabld.productdelivery.stage.mozaws.net: IGW

            # papertrail servers
            173.247.96.0/19: IGW
            67.214.208.0/20: IGW
            169.46.82.160/27: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    testers:
        routes:
            # Amazon routes (check via 'whois')
            AMAZON: IGW

            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    builders:
        routes:
            # Amazon routes (check via 'whois')
            AMAZON: IGW

            # Mozilla stuff
            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.ffxbld.productdelivery.prod.mozaws.net: IGW
            upload.tbirdbld.productdelivery.prod.mozaws.net: IGW
            upload.seabld.productdelivery.prod.mozaws.net: IGW
            upload.ffxbld.productdelivery.stage.mozaws.net: NAT
            upload.tbirdbld.productdelivery.stage.mozaws.net: NAT
            upload.seabld.productdelivery.stage.mozaws.net: IGW
            crash-stats.mozilla.com: IGW
            queue.taskcluster.net: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW
    try:
        routes:
            # Amazon routes
            AMAZON: IGW

            # Mozilla stuff
            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.trybld.productdelivery.prod.mozaws.net: IGW
            upload.trybld.productdelivery.stage.mozaws.net: NAT
            queue.taskcluster.net: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    signing:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            # papertrail servers
            173.247.96.0/19: IGW
            67.214.208.0/20: IGW
            169.46.82.160/27: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    upload-nat:
        routes:
            10.132.0.0/16: local
            0.0.0.0/0: IGW


us-east-1:
    default:
        routes:
            10.134.0.0/16: local
            0.0.0.0/0: VGW

    masters:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.ffxbld.productdelivery.prod.mozaws.net: IGW
            upload.trybld.productdelivery.prod.mozaws.net: IGW
            upload.tbirdbld.productdelivery.prod.mozaws.net: IGW
            upload.ffxbld.productdelivery.stage.mozaws.net: NAT
            upload.trybld.productdelivery.stage.mozaws.net: NAT
            upload.tbirdbld.productdelivery.stage.mozaws.net: NAT
            # seabld only here to appease firewall-test complexity, no harm
            upload.seabld.productdelivery.prod.mozaws.net: IGW
            upload.seabld.productdelivery.stage.mozaws.net: IGW

            # papertrail servers
            173.247.96.0/19: IGW
            67.214.208.0/20: IGW
            169.46.82.160/27: IGW

            10.134.0.0/16: local
            0.0.0.0/0: VGW

    testers:
        routes:
            # Amazon routes
            AMAZON: IGW

            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            10.134.0.0/16: local
            0.0.0.0/0: VGW

    builders:
        routes:
            # Amazon routes
            AMAZON: IGW

            # Mozilla stuff
            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.ffxbld.productdelivery.prod.mozaws.net: IGW
            upload.tbirdbld.productdelivery.prod.mozaws.net: IGW
            upload.seabld.productdelivery.prod.mozaws.net: IGW
            upload.ffxbld.productdelivery.stage.mozaws.net: NAT
            upload.tbirdbld.productdelivery.stage.mozaws.net: NAT
            upload.seabld.productdelivery.stage.mozaws.net: IGW
            crash-stats.mozilla.com: IGW
            queue.taskcluster.net: IGW

            10.134.0.0/16: local
            0.0.0.0/0: VGW

    try:
        routes:
            # Amazon routes
            AMAZON: IGW

            # Mozilla stuff
            hg.mozilla.org: IGW
            git.mozilla.org: IGW
            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW
            upload.trybld.productdelivery.prod.mozaws.net: IGW
            upload.trybld.productdelivery.stage.mozaws.net: NAT
            queue.taskcluster.net: IGW

            10.134.0.0/16: local
            0.0.0.0/0: VGW


    "EB: NAT1":
        routes:
            10.134.0.0/16: local
            10.0.0.0/8: VGW
            0.0.0.0/0: i-0dc6a56a

    "EB: NAT2":
        routes:
            10.134.0.0/16: local
            10.0.0.0/8: VGW
            0.0.0.0/0: IGW

    signing:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            # papertrail servers
            173.247.96.0/19: IGW
            67.214.208.0/20: IGW
            169.46.82.160/27: IGW

            10.134.0.0/16: local
            0.0.0.0/0: VGW

    upload-nat:
        routes:
            10.134.0.0/16: local
            0.0.0.0/0: IGW
