# Macros that can be included below; see yaml_includes.py.  Be careful in applying these:
# the include processor doesn't automatically flatten lists or anything like that.
includes:

    # ping is allowed from anywhere in just about every SG
    global-ping:
        proto: icmp
        ports: [-1]
        hosts:
          - 0.0.0.0/0

    # most outgoing flows are completely open
    global-any:
        proto: -1
        hosts:
          - 0.0.0.0/0

    jumphost-admin-access:
        proto: tcp
        ports: [22, 3389, 5900]
        hosts:
          - rejh1.srv.releng.scl3.mozilla.com  # 10.26.48.19
          - rejh2.srv.releng.scl3.mozilla.com  # 10.26.48.20
          - rejh1.srv.releng.mdc1.mozilla.com  # 10.49.48.100
          - rejh2.srv.releng.mdc1.mozilla.com  # 10.49.48.101

    nagios-nrpe:
        proto: tcp
        ports: [5666]
        hosts:
          - nagios1.private.releng.scl3.mozilla.com
          - nagios1.private.releng.mdc1.mozilla.com

    # all slave VLANs look the same
    slave-vlan-inbound:
        - proto: tcp
          ports: [22]
          hosts:
            - {include: slaveapi-servers}
            - aws-manager1.srv.releng.scl3.mozilla.com
            - aws-manager2.srv.releng.scl3.mozilla.com
        - include: jumphost-admin-access
        - include: global-ping

    outbound-http-https:
        proto: tcp
        ports: [80,443]
        hosts:
            - 0.0.0.0/0

    outbound-git:
        proto: tcp
        ports: [9418,22]  # N.B. allows SSH too
        hosts:
            - 192.30.252.0/22 # github (https://api.github.com/meta)
            - 198.145.11.235/32  # codeaurora

    outbound-ssh-upload-build:
        proto: tcp
        ports: [22]
        hosts:
            - upload.tbirdbld.productdelivery.prod.mozaws.net
            - upload.tbirdbld.productdelivery.stage.mozaws.net
            - upload.ffxbld.productdelivery.prod.mozaws.net
            - upload.ffxbld.productdelivery.stage.mozaws.net
            - upload.seabld.productdelivery.prod.mozaws.net
            - upload.seabld.productdelivery.stage.mozaws.net

    outbound-ssh-upload-try:
        proto: tcp
        ports: [22]
        hosts:
            - upload.trybld.productdelivery.prod.mozaws.net
            - upload.trybld.productdelivery.stage.mozaws.net

    outbound-amqp-amqps:
        proto: tcp
        ports: [5671, 5672]
        hosts:
            - orange-antelope.rmq.cloudamqp.com
            - orange-antelope-01.rmq.cloudamqp.com
            - orange-antelope-02.rmq.cloudamqp.com
            - orange-antelope-03.rmq.cloudamqp.com

    outbound-stun-tcp:
        proto: tcp
        ports: [42]
        hosts:
            - 23.21.150.121/32
            - expo.mit.edu
            - 216.93.246.14/32

    outbound-stun-udp:
        proto: udp
        ports: [42]
        hosts:
            - 23.21.150.121/32
            - expo.mit.edu
            - 216.93.246.14/32

    outbound-carbon:
        proto: tcp
        ports: [2003]
        hosts:
            - 0.0.0.0/0

    outbound-irc:
        proto: tcp
        ports: [6697]
        hosts:
            - 54.72.42.192/32
            - 54.219.165.167/32
            - 54.85.60.193/32
            - 63.245.216.214/32

    outbound-ntp:
        proto: udp
        ports: [123]
        hosts:
            - 0.0.0.0/0

    outbound-papertrail:
        proto: tcp
        ports: [45266]
        hosts:
            - 67.214.208.0/20
            - 173.247.96.0/19

    outbound-mozilla:
        # all outbound traffic to mozilla nets is filtered at the destination
        proto: -1
        hosts:
            # Private IP space
            - 10.0.0.0/8
            # Mozilla's public IP space
            - 63.245.208.0/20

    test-slave-vlan-outbound:
        - include: outbound-mozilla
        - include: outbound-http-https
        - include: outbound-git
        - include: outbound-amqp-amqps
        - include: outbound-stun-tcp
        - include: outbound-stun-udp
        - include: outbound-carbon
        - include: outbound-ntp
        - include: global-ping

    try-slave-vlan-outbound:
        - include: outbound-mozilla
        - include: outbound-http-https
        - include: outbound-git
        - include: outbound-ssh-upload-try
        - include: outbound-amqp-amqps
        - include: outbound-stun-tcp
        - include: outbound-stun-udp
        - include: outbound-carbon
        - include: outbound-ntp
        - include: global-ping

    build-slave-vlan-outbound:
        - include: outbound-mozilla
        - include: outbound-http-https
        - include: outbound-git
        - include: outbound-ssh-upload-build
        - include: outbound-amqp-amqps
        - include: outbound-stun-tcp
        - include: outbound-stun-udp
        - include: outbound-carbon
        - include: outbound-ntp
        - include: global-ping

    slave-vlan-outbound:
        - include: global-any

    # host set aliases:
    slaveapi-servers: 10.26.48.16/31

    # network aliases:
    build-scl3: 10.26.52.0/22
    test-scl3: 10.26.56.0/22
    try-scl3: 10.26.64.0/22
    winbuild-scl3: 10.26.36.0/22
    wintest-scl3: 10.26.40.0/22
    wintry-scl3: 10.26.44.0/22
    pods-scl3: 10.26.128.0/17
    build-usw2: 10.132.52.0/22
    test-usw2: 10.132.56.0/22
    test2-usw2: 10.132.156.0/22
    test3-usw2: 10.132.40.0/21
    test4-usw2: 10.132.60.0/22
    try-usw2: 10.132.64.0/22
    build-use1: 10.134.52.0/22
    build2-use1: 10.134.164.0/24
    test-use1: 10.134.56.0/22
    test2-use1: 10.134.156.0/22
    test3-use1: 10.134.40.0/21
    test4-use1: 10.134.60.0/22
    test5-use1: 10.134.160.0/22
    try-use1: 10.134.64.0/22
    try2-use1: 10.134.165.0/24
    slave-vlans:
      - {include: build-scl3}
      - {include: test-scl3}
      - {include: try-scl3}
      - {include: winbuild-scl3}
      - {include: wintest-scl3}
      - {include: wintry-scl3}
      - {include: pods-scl3}
      - {include: build-usw2}
      - {include: test-usw2}
      - {include: test2-usw2}
      - {include: test3-usw2}
      - {include: test4-usw2}
      - {include: try-usw2}
      - {include: build-use1}
      - {include: build2-use1}
      - {include: test-use1}
      - {include: test2-use1}
      - {include: test3-use1}
      - {include: test4-use1}
      - {include: test5-use1}
      - {include: try-use1}
      - {include: try2-use1}

    # and port aliases
    buildbot-http-portrange: 8000-8999
    buildbot-rpc-portrange: 9000-9999

    aws-manager-ssh:
      proto: tcp
      ports: [22]
      hosts:
        - aws-manager1.srv.releng.scl3.mozilla.com
        - aws-manager2.srv.releng.scl3.mozilla.com

tests:
    description: security group for test slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, tst-linux*]
                - [Name, tst-linux*-ec2-*]
        interfaces:
            tags:
                - [moz-type, tst-linux*]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: test-slave-vlan-outbound

build:
    description: security group for build slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, bld-linux64]
                - [moz-type, av-linux64]
                - [moz-type, b-2008]
                - [Name, bld-linux64-ec2-*]
                - [Name, av-linux64-ec2-*]
                - [Name, b-2008-ec2-*]
        interfaces:
            tags:
                - [moz-type, bld-linux64]
                - [moz-type, av-linux64]
                - [moz-type, b-2008]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: build-slave-vlan-outbound

try:
    description: security group for try build slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, try-linux64]
                - [moz-type, y-2008]
                - [Name, try-linux64-ec2-*]
                - [Name, y-2008-ec2-*]
        interfaces:
            tags:
                - [moz-type, try-linux64]
                - [moz-type, y-2008]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: try-slave-vlan-outbound

loaners:
    description: secondary security group adds non-release access to test/build/try slave loaners
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [22, 3389, 5900]
          hosts:
            - 10.22.240.0/20  # scl3-vpn-net
            - ssh1.corpdmz.scl3.mozilla.com

buildbot-master:
    description: security group for buildbot masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        # traffic from other masters
        - proto: tcp
          ports:
            - 22  # ssh
            - {include: buildbot-rpc-portrange}
            - {include: buildbot-http-portrange}
          hosts:
            - 10.26.68.0/24  # bb.releng.scl3
            - 10.132.68.0/24  # bb.releng.usw2
            - 10.134.68.0/24  # bb.releng.use1

        # traffic from buildslaves
        - proto: tcp
          ports:
            - {include: buildbot-rpc-portrange}
          hosts: {include: slave-vlans}

        # buildbot-http from aws-managers and slaveapi
        - proto: tcp
          ports:
            - {include: buildbot-http-portrange}
          hosts:
            - {include: slaveapi-servers}
            - aws-manager1.srv.releng.scl3.mozilla.com
            - aws-manager2.srv.releng.scl3.mozilla.com
            - 10.22.240.0/20  # scl3-vpn-net
            - ssh1.corpdmz.scl3.mozilla.com

        # traffic from buildduty-tools
        - proto: tcp
          ports:
            - 22  # ssh
            - {include: buildbot-http-portrange}
          hosts:
            - buildduty-tools.srv.releng.usw2.mozilla.com

        # generic stuff
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

puppet-master:
    description: security group for puppet masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [443, 80, 8140]
          hosts:
            - 10.26.0.0/16
            - 10.49.0.0/16
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16
            - nagios1.private.releng.scl3.mozilla.com
            - nagios1.private.releng.mdc1.mozilla.com

        # Only distinguished masters need inbound ssh from other masters

        # generic stuff
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

blobber:
    description: security group for blobber service
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [443]
          hosts: {include: slave-vlans}
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

# proxxy is configured per-region; these two stanzas should be kept parallel
proxxy-vpc-use1:
    description: security group for proxxy servers in use1
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-use1}
            - {include: build2-use1}
            - {include: test-use1}
            - {include: test2-use1}
            - {include: test3-use1}
            - {include: test4-use1}
            - {include: test5-use1}
            - {include: try-use1}
            - {include: try2-use1}
            - nagios1.private.releng.scl3.mozilla.com
            - nagios1.private.releng.mdc1.mozilla.com
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

proxxy-vpc-usw2:
    description: security group for proxxy servers in usw2
    regions:
        us-west-2: vpc-cd63f2a4
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-usw2}
            - {include: test-usw2}
            - {include: test2-usw2}
            - {include: test3-usw2}
            - {include: test4-usw2}
            - {include: try-usw2}
            - nagios1.private.releng.scl3.mozilla.com
            - nagios1.private.releng.mdc1.mozilla.com
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

LogAggregators:
    description: Group for log aggregators and their load balancer
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [1514]
          hosts:
            - 10.26.0.0/16
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16
            - nagios1.private.releng.scl3.mozilla.com
            - nagios1.private.releng.mdc1.mozilla.com
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

VCSSync:
    description: Group hg/git vcssync servers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

signing-worker:
    description: security group for signing workers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

balrogworker:
    description: security group for balrogworkers
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

beetmoverworker:
    description: security group for beetmoverworkers
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

bouncerworker:
    description: security group for bouncer_scriptworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

pushapkworker:
    description: security group for pushapkworker
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

shipitworker:
    description: security group for shipitworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

binarytransparencyworker:
    description: security group for binary transparency worker
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

treescriptworker:
    description: security group for treescriptworker
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: aws-manager-ssh
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any
