tests:
    description: security group for test slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, tst-linux*]
                - [Name, tst-linux*-ec2-*]
        interfaces:
            tags:
                - [moz-type, tst-linux*]
    inbound:
        - proto: tcp
          ports: [22, 5900]
          hosts:
            - cruncher.build.mozilla.org
            - slaveapi1.srv.releng.scl3.mozilla.com
            - slaveapi-dev1.srv.releng.scl3.mozilla.com
            - 10.22.252.0/22
            - 10.22.248.0/22
            - dev-master1.build.mozilla.org
            - aws-manager1.srv.releng.scl3.mozilla.com
        - proto: icmp
          ports: [-1]
          hosts:
            - 10.22.252.0/22
            - 10.22.248.0/22
            - cruncher.build.mozilla.org
            - slaveapi1.srv.releng.scl3.mozilla.com
            - slaveapi-dev1.srv.releng.scl3.mozilla.com
            - dev-master1.build.mozilla.org
            - aws-manager1.srv.releng.scl3.mozilla.com


    outbound:
        - proto: -1
          hosts:
            - 0.0.0.0/0

build:
    description: security group for build slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, bld-linux64]
                - [Name, bld-linux64-ec2-*]
        interfaces:
            tags:
                - [moz-type, bld-linux64]
    inbound:
        - proto: tcp
          ports: [22, 5900]
          hosts:
            - cruncher.build.mozilla.org
            - slaveapi1.srv.releng.scl3.mozilla.com
            - slaveapi-dev1.srv.releng.scl3.mozilla.com
            - 10.22.252.0/22
            - 10.22.248.0/22
            - dev-master1.build.mozilla.org
            - aws-manager1.srv.releng.scl3.mozilla.com
        - proto: icmp
          ports: [-1]
          hosts:
            - 10.22.252.0/22
            - 10.22.248.0/22
            - cruncher.build.mozilla.org
            - slaveapi1.srv.releng.scl3.mozilla.com
            - slaveapi-dev1.srv.releng.scl3.mozilla.com
            - dev-master1.build.mozilla.org
            - aws-manager1.srv.releng.scl3.mozilla.com


    outbound:
        - proto: -1
          hosts:
            - 0.0.0.0/0
