us-west-2:
    vpc-cd63f2a4:
        10.132.48.0/22:
            name: srv
            routing_table: masters

        10.132.52.0/22:
            name: build
            routing_table: builders

        10.132.56.0/22:
            name: test
            routing_table: testers

        10.132.64.0/22:
            name: try
            routing_table: try

        10.132.68.0/24:
            name: bb
            routing_table: masters

        10.132.156.0/22:
            name: test
            routing_table: testers

        10.132.80.0/23:
            name: build.servo
            routing_table: default

        10.132.82.0/23:
            name: srv.servo
            routing_table: default

us-east-1:
    vpc-b42100df:
        10.134.48.0/22:
            name: srv
            routing_table: masters

        10.134.52.0/22:
            name: build
            routing_table: builders

        10.134.56.0/22:
            name: test
            routing_table: testers

        10.134.64.0/22:
            name: try
            routing_table: try

        10.134.68.0/24:
            name: bb
            routing_table: masters

        10.134.156.0/22:
            name: test
            routing_table: testers
            skip_azs: []

        10.134.80.0/23:
            name: build.servo
            routing_table: default

        10.134.82.0/23:
            name: srv.servo
            routing_table: default
